name: ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and push Docker images
    strategy:
      fail-fast: true
      matrix:
        image:
          - "3.6.6-stretch"
          - "3.7-slim"
          - "3.7-stretch"
          - "3.8-slim"
          - "3.9-alpine"
          - "3.9-buster"
          - "3.9-slim"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build and push
        env:
          POETRY_VERSION: 1.1.4
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ matrix.image }},${{ matrix.image }}-${{ env.CURRENT_DATE }},${{ matrix.image }}-${{ env.POETRY_VERSION }},${{ matrix.image }}-${{ env.POETRY_VERSION }}-${{ env.CURRENT_DATE }}
