name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and push Docker images
    strategy:
      fail-fast: true
      matrix:
        os:
          - "alpine"
          - "buster"
          - "bullseye"
          - "slim"
        version:
          - "3.7"
          - "3.7.12"
          - "3.8"
          - "3.8.12"
          - "3.9"
          - "3.9.9"
          - "3.9.10"
          - "3.10"
          - "3.10.0"
          - "3.10.1"
          - "3.10.2"
          - "3.10.3"
          - "3.10.4"
          - "3.10.5"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build and push
        env:
          POETRY_VERSION: 1.2.1
          DOCKER_REPOSITORY: duffn/python-poetry
        uses: docker/build-push-action@v2
        with:
          context: ./docker/${{ matrix.os }}/${{ matrix.version }}
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.CURRENT_DATE }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}-${{ env.CURRENT_DATE }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.CURRENT_DATE }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}-${{ env.CURRENT_DATE }}
