name: ci

on:
  push:
    branches:
      - "main"
      - duffn/generate

env:
  POETRY_VERSION: 1.4.1

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Dockerfiles
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: Generate Dockerfiles
        run: python generate.py
      - name: Delete old cache
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          gh actions-cache delete dockerfiles --repo $REPO --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Dockerfiles
        uses: actions/cache@v3
        with:
          path: docker
          key: dockerfiles

  docker:
    needs: generate
    runs-on: ubuntu-latest
    name: Build and push Docker images
    strategy:
      fail-fast: false
      matrix:
        os:
          - "alpine"
          - "buster"
          - "bullseye"
          - "slim"
        version:
          - "3.7"
          - "3.7.12"
          - "3.7.13"
          - "3.7.14"
          - "3.7.15"
          - "3.7.16"
          - "3.8"
          - "3.8.12"
          - "3.8.13"
          - "3.8.14"
          - "3.8.15"
          - "3.8.16"
          - "3.9"
          - "3.9.9"
          - "3.9.10"
          - "3.9.11"
          - "3.9.12"
          - "3.9.13"
          - "3.9.14"
          - "3.9.15"
          - "3.9.16"
          - "3.10"
          - "3.10.0"
          - "3.10.1"
          - "3.10.2"
          - "3.10.3"
          - "3.10.4"
          - "3.10.5"
          - "3.10.6"
          - "3.10.7"
          - "3.10.8"
          - "3.10.9"
          - "3.10.10"
          - "3.11"
          - "3.11.0"
          - "3.11.1"
          - "3.11.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check cache
        id: check-cache
        uses: actions/cache@v3
        with:
          path: docker
          key: dockerfiles
          fail-on-cache-miss: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build and push
        env:
          DOCKER_REPOSITORY: duffn/python-poetry
        uses: docker/build-push-action@v2
        with:
          context: ./docker/${{ matrix.os }}/${{ matrix.version }}
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.CURRENT_DATE }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}
            ${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}-${{ env.CURRENT_DATE }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.CURRENT_DATE }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ matrix.version }}-${{ matrix.os }}-${{ env.POETRY_VERSION }}-${{ env.CURRENT_DATE }}
